<a href="https://colab.research.google.com/github/divana1/Homeworks/blob/main/Homework_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import Binarizer
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier
import pandas as pd


In [ ]:
os.chdir('/content/drive/MyDrive/data ML')

Раздел 1. Предварительная обработка данных
1.	Укажите путь к рабочей папке, где хранятся данные, с помощью функции chdir() из модуля os.
2.	Загрузите данные файла pima-indians-diabetes.data.csv с помощью функции read_csv() из модуля pandas. Посмотрите на первые 5 наблюдений с помощью функции head().





3.	Сохраните в переменную array значения признаков, обратившись к атрибуту values.
4.	Выделите в переменной array часть, которая относится к факторным признакам, назовите ее X, и часть, которая относится к результативному признаку, - Y. Прокомментируйте содержимое переменных X и Y.



5.	Проведите масштабирование факторных признаков на отрезок [0,1]. Для этого сначала создайте соответствующий объект с помощью функции MinMaxScaler() из модуля sklearn.preprocessing. Потом обучите его на факторных признаках и преобразуйте данные с помощью функции fit_transform().
6.	Установите формат представления данных вида 3 знака после запятой, воспользовавшись функцией set_printoptions() из модуля numpy.
7.	Выведите на экран первые 5 строк преобразованных данных.


In [ ]:
data=read_csv('/content/drive/MyDrive/data ML/country-wise-average.csv')
data.head()

Country  Income Classification  Severe Wasting    Wasting  Overweight  \
0  AFGHANISTAN                    0.0        3.033333  10.350000    5.125000   
1      ALBANIA                    2.0        4.075000   7.760000   20.800000   
2      ALGERIA                    2.0        2.733333   5.942857   12.833333   
3       ANGOLA                    1.0        2.400000   6.933333    2.550000   
4    ARGENTINA                    2.0        0.200000   2.150000   11.125000   

    Stunting  Underweight  U5 Population ('000s)  
0  47.775000    30.375000            4918.561500  
1  24.160000     7.700000             232.859800  
2  19.571429     7.342857            3565.213143  
3  42.633333    23.600000            3980.054000  
4  10.025000     2.600000            3613.651750

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 152 entries, 0 to 151
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                152 non-null    object 
 1   Income Classification  152 non-null    float64
 2   Severe Wasting         140 non-null    float64
 3   Wasting                150 non-null    float64
 4   Overweight             149 non-null    float64
 5   Stunting               151 non-null    float64
 6   Underweight            150 non-null    float64
 7   U5 Population ('000s)  152 non-null    float64
dtypes: float64(7), object(1)
memory usage: 9.6+ KB


In [ ]:
data.describe()

Income Classification  Severe Wasting     Wasting  Overweight  \
count             152.000000      140.000000  150.000000  149.000000   
mean                1.427632        2.168650    6.599257    7.201638   
std                 0.967019        1.708939    4.481723    4.649144   
min                 0.000000        0.000000    0.000000    0.962500   
25%                 1.000000        0.900000    3.262500    3.850000   
50%                 1.000000        1.872500    5.710714    6.300000   
75%                 2.000000        2.822727    8.740476    9.080000   
max                 3.000000       11.400000   23.650000   26.500000   

         Stunting  Underweight  U5 Population ('000s)  
count  151.000000   150.000000             152.000000  
mean    25.814728    13.503047            4042.927052  
std     14.686807    10.895839           13164.191927  
min      1.000000     0.100000               1.000000  
25%     13.485000     4.305000             241.765813  
50%     24.160000    10.380000             981.233486  
75%     36.564935    19.496875            3002.433080  
max     57.600000    46.266667          123014.491000

In [ ]:
df = data.dropna()

In [ ]:
array=df.values

In [ ]:
X=array[:,3:8]
Y=array[:,2]

In [ ]:
Y=Y.astype('int')

In [ ]:
scaler=MinMaxScaler(feature_range=(0,1))

In [ ]:
rescaledX=scaler.fit_transform(X)

In [ ]:
set_printoptions(precision=3) 

In [ ]:
print(rescaledX[0:5,:])

[[0.438 0.163 0.826 0.656 0.04 ]
 [0.328 0.777 0.409 0.165 0.002]
 [0.251 0.465 0.328 0.157 0.029]
 [0.293 0.062 0.736 0.509 0.032]
 [0.091 0.398 0.159 0.054 0.029]]


8. Проведите стандартизацию факторных признаков. Для этого сначала создайте соответствующий объект с помощью функции StandardScaler() из модуля sklearn.preprocessing. Потом обучите его на факторных признаках с помощью функции fit() и преобразуйте данные с помощью функции transform(). Выведите на экран первые 5 строк преобразованных данных

In [ ]:
scaler=StandardScaler().fit(X)

In [ ]:
rescaledX=scaler.transform(X)

In [ ]:
data.head(5)

Country  Income Classification  Severe Wasting    Wasting  Overweight  \
0  AFGHANISTAN                    0.0        3.033333  10.350000    5.125000   
1      ALBANIA                    2.0        4.075000   7.760000   20.800000   
2      ALGERIA                    2.0        2.733333   5.942857   12.833333   
3       ANGOLA                    1.0        2.400000   6.933333    2.550000   
4    ARGENTINA                    2.0        0.200000   2.150000   11.125000   

    Stunting  Underweight  U5 Population ('000s)  
0  47.775000    30.375000            4918.561500  
1  24.160000     7.700000             232.859800  
2  19.571429     7.342857            3565.213143  
3  42.633333    23.600000            3980.054000  
4  10.025000     2.600000            3613.651750

9.9.	Проведите нормализацию факторных признаков. Для этого сначала создайте соответствующий объект с помощью функции Normalizer() из модуля sklearn.preprocessing. Потом обучите его на факторных признаках с помощью функции fit() и преобразуйте данные с помощью функции transform(). Выведите на экран первые 5 строк преобразованных данных.

In [ ]:
scaler=Normalizer().fit(X)

In [ ]:
rescaledX=scaler.transform(X)

In [ ]:
print(rescaledX[0:5,:])

[[2.104e-03 1.042e-03 9.713e-03 6.175e-03 9.999e-01]
 [3.298e-02 8.840e-02 1.027e-01 3.273e-02 9.897e-01]
 [1.667e-03 3.600e-03 5.489e-03 2.060e-03 1.000e+00]
 [1.742e-03 6.406e-04 1.071e-02 5.929e-03 9.999e-01]
 [5.950e-04 3.079e-03 2.774e-03 7.195e-04 1.000e+00]]


10.	Проведите бинарное кодирование факторных признаков так, чтобы значение признака, большее 0, стало равным 1. Для этого сначала создайте соответствующий объект с помощью функции Binarizer(threshold=0.0) из модуля sklearn.preprocessing. Потом обучите его на факторных признаках с помощью функции fit() и преобразуйте данные с помощью функции transform(). Выведите на экран первые 5 строк преобразованных данных.

In [ ]:
bin=Binarizer(threshold=0.0).fit(X)

In [ ]:
binaryX=bin.transform(X)

In [ ]:
print(binaryX[0:5,:])

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


11.	Проведите отбор 4 наиболее значимых признаков на основе F-критерия в дисперсионном анализе. Для этого сначала создайте соответствующий объект с помощью функции SelectKBest(score_func=f_classif, k=4) из модуля sklearn.feature_selection. Потом обучите его на переменных X и Y с помощью функции fit(). Выведите на экран значения F-критерия для всех признаков, обратившись к параметру scores_.

In [ ]:
test=SelectKBest(score_func=f_classif, k=4)

In [ ]:
fit=test.fit(X,Y)

In [ ]:
print(fit.scores_)

[74.6    0.734  7.75  16.751 21.007]



12.	Преобразуйте факторные признаки с помощью функции transform(). Выведите на экран первые 5 строк преобразованных данных.


In [ ]:
features=fit.transform(X)

In [ ]:
print(features[0:5,:])

[[10.35 47.775000000000006 30.375 4918.5615]
 [7.76 24.16 7.7 232.8598]
 [5.942857142857143 19.571428571428573 7.3428571428571425
  3565.213142857144]
 [6.933333333333333 42.63333333333333 23.600000000000005 3980.054]
 [2.1500000000000004 10.025 2.6 3613.65175]]


13.	Проводите рекурсивное исключение наименее значимых признаков до тех пор, пока не останется 3 признака. Отбор осуществляйте на основе модели логистической регрессии. Сначала создайте модель с помощью функции LogisticRegression() из модуля sklearn.linear_model. 

In [ ]:
model=LogisticRegression(solver='liblinear')

14.	Затем с помощью функции RFE() из модуля sklearn.feature_selection создайте объект для рекурсивного исключения признаков, подав ему на вход созданную модель логистической регрессии и количество отбираемых признаков (n_features_to_select=3). 

In [ ]:
rfe=RFE(model,n_features_to_select=3) 

15.	Обучите созданный объект на переменных X и Y с помощью функции fit(). 

In [ ]:
fit=rfe.fit(X,Y)

16.	Выведите на экран число отобранных признаков, обратившись к параметру n_features_.

In [ ]:
fit.n_features_

3

17.	Выведите на экран логическое указание на отобранные признаки из всего набора, обратившись к параметру support_.


In [ ]:
fit.support_

array([ True,  True, False,  True, False])

18.	Выведите на экран ранги признаков, обратившись к параметру ranking_.



In [ ]:
fit.ranking_

array([1, 1, 2, 1, 3])

19.	Преобразуйте факторные признаки с помощью функции fit_transform(). Выведите на экран первые 5 строк преобразованных данных.

In [ ]:
tr = rfe.fit_transform(X,Y)
print(tr[0:5,:])

[[10.35 5.125 30.375]
 [7.76 20.8 7.7]
 [5.942857142857143 12.833333333333334 7.3428571428571425]
 [6.933333333333333 2.55 23.600000000000005]
 [2.1500000000000004 11.125 2.6]]


20.	Проведите отбор 3-х главных компонент. Для этого сначала создайте соответствующий объект с помощью функции PCA(n_components=3) из модуля sklearn.decomposition. 

In [ ]:
pca=PCA(n_components=3)

21.	Обучите его на факторных признаках с помощью функции fit().

In [ ]:
fit=pca.fit(X)

22.	Выведите на экран долю объясненной 3-мя компонентами дисперсии, обратившись к параметру explained_variance_ratio_.

In [ ]:
fit.explained_variance_ratio_

array([1.000e+00, 1.708e-06, 1.580e-07])

23.	Выведите на экран компонентные нагрузки, обратившись к параметру components_. Что они показывают?

In [ ]:
fit.components_

array([[ 6.252e-05, -3.676e-05,  1.573e-04,  1.868e-04,  1.000e+00],
       [ 1.719e-01, -1.192e-01,  7.923e-01,  5.731e-01, -2.468e-04],
       [ 3.920e-01, -4.497e-01, -5.650e-01,  5.700e-01, -5.861e-05]])

24.	Вычислите на основе факторных признаков главные компоненты, обратившись к функции fit_transform(). Выведите на экран первые 5 наблюдений.

In [ ]:
tr1 = pca.fit_transform(X)
print(tr1[0:5,:])

[[ 6.129e+02  2.688e+01 -1.984e-01]
 [-4.073e+03 -5.981e+00 -7.570e+00]
 [-7.405e+02 -1.001e+01 -2.506e+00]
 [-3.256e+02  1.888e+01 -1.281e+00]
 [-6.921e+02 -2.075e+01 -5.371e-01]]


25.	Примените классификатор дополнительных деревьев для отбора признаков, воспользовавшись встроенным в них механизмом расчета критериев информативности при поиске, по какому признаку осуществлять разбиение. Для этого сначала создайте соответствующий объект с помощью функции ExtraTreesClassifier(n_estimators=100) из модуля sklearn.ensemble.
26.	Обучите его на переменных X и Y с помощью функции fit().


In [ ]:
model=ExtraTreesClassifier(n_estimators=100)

In [ ]:
model.fit(X,Y)

ExtraTreesClassifier()

27. Выведите на экран значения критерия информативности для каждого признака, обратившись к параметру feature_importances_.

In [ ]:
print(model.feature_importances_)

[0.382 0.158 0.153 0.191 0.116]
